services:
  - type: web
    name: spring-boot-app
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: DATASOURCE_URL
        fromDatabase:
          name: spring-db
          property: connectionString
      - key: DATABASE_USER
        fromDatabase:
          name: spring-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: spring-db
          property: password
